### ISSUE TITLE
Render markdown with jsoninclude-quote directives

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#103]
Definitions rendered within `jsoninclude-quote` directives may contain links. At present these links are rendering as plain text within definitions - see [example](https://open-fibre-data-standard.readthedocs.io/en/main/reference/schema.html#geometry). On a quick look the solution didn't appear to be as simple as using the [markdown directive](https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/misc/#directive-markdown) within the `jsoninclude-quote` directive, but I haven't looked in detail.

**Comment by duncandewhurst** [comment]
@bjwebb is likely going to look at this next week. I don't think it's a blocker for the alpha release.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/126
