### ISSUE TITLE
Add an admonition to each page with consultation instructions

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#109]
The instructions can explain the different options for providing feedback and provide a steer as to the key issues on which we are seeking feedback.

At the same time we can remove the admonition that currently appears on the home page.

**Comment by duncandewhurst** [comment]
I think that we want to keep the admonition brief and put most of the content in an announcement post in the discussions section of the repo. That way we can update the instructions without needing to update the standard. I've drafted the following as a starter for ten:

## Admonition

Add an admonition immediately below the title of each documentation page with the following content:

> **Alpha release**
> Welcome to the alpha release of the Open Fibre Data Standard.
> 
> We want to hear your feedback on the standard and its documentation. To find out how you can provide feedback, read the [alpha release announcement](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/115).

## Announcement post

> We're pleased to announce the alpha release of the Open Fibre Data Standard.
> 
> We are seeking feedback on the standard and its documentation. You can use the [consultation form](https://forms.gle/GX9bMgc8nCXh1EWv7) to provide structured feedback, or you can provide feedback via the following channels:
> 
> * For general feedback, questions and suggestions, you can comment on this discussion or [start a new discussion](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/new).
> * For bug reports or feedback on specific elements of the data model and documentation, you can comment on the issues linked in the documentation or you can [create a new issue](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/new/choose).
> * If you prefer to provide feedback privately, you can email info@opentelecomdata.net.
> 
> To comment on or create discussions and issues, you need to [sign up for a free GitHub account](https://github.com/signup).
> 
> Please provide feedback by **11th October 2022**.

**Comment by lgs85** [comment]
@duncandewhurst I'll leave this open until the announcement post is up

**Comment by duncandewhurst** [comment]
I've released the alpha and updated the announcement post: https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/115
