### ISSUE TITLE
Node/link elevation

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#11]
The [supply side research](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/5) did not surface any examples of existing datasets in which the elevation of either nodes or links were specified. Similarly, the [demand side research](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/4) did not surface a particular demand for this data.

However, I can think of scenarios in which this might be useful, for example:

* If you're looking at connecting to an existing link, it's useful to know it runs through a tunnel (as in [planned](https://www.crowninfrastructure.govt.nz/wp-content/uploads/2019/04/CIP-South-Westland-Milford-Briefing.pdf) for the Homer tunnel in New Zealand) or over the landscape, especially for long distance tunnels.
* The elevation of a node might be useful for planning line of sight microwave links.

We should check that whatever solutions we settle on for representing node locations and link routes can support including an elevation element.

**Comment by stevesong** [comment]
I am not opposed to this but would want to be more convinced of the value added.  For the latter example of microwave links, this is typically done in a wireless planning tools like CloudRF or similar which integrates elevation.  For the tunnel example, how would the elevation be recorded?  As an average over the link or at the node points?

**Comment by duncandewhurst** [comment]
Yes, I don't think elevation data is a high priority. However, coordinations in GeoJSON [may include an elevation element](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1) so, in the JSON and GeoJSON formats, elevation will be supported by default. This issue serves as a reminder not to break that support in the CSV format.

> For the latter example of microwave links, this is typically done in a wireless planning tools like CloudRF or similar which integrates elevation

Good to know. Do tools like that calculate the elevation based on the ground level at the longitude and latitude?

> For the tunnel example, how would the elevation be recorded? As an average over the link or at the node points?

I was imagining that that the link's route would be defined by a polyline, the points of which would include an elevation element. That way, even if a tunnel was straight and perfectly level, a link through it could be represented by 3 points: one at each end and one at the midpoint.

**Comment by duncandewhurst** [comment]
> This issue serves as a reminder not to break that support in the CSV format.

Elevation is supported in the CSV format so I'm going to close this issue. It can be reopened if the topic of elevation comes up again.

**Comment by duncandewhurst** [comment]
@stevesong copying your comment on deployment depth from https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/308 to this related issue:

> Adjacent to this, we may also wish to specifically capture depth of deployment for underground fibre, for a couple of reasons. The first is a quality issue in that deeper deployments tend to be more robust. The second is that there may be coordination issues with other infrastructure being deployed along the same route but at a different depth.

I haven't thought about it in detail, but deployment depth could vary over the course of a span, so we'd need to consider how to handle that.

**Comment by stevesong** [comment]
I raise it because the notion of 3D GIS data for underground cables was presented by one of the European regulator participants in the Malawi - Africa BB Mapping workshop.  I can't imagine depth (or at least intended depth) varying over the course of a span but this probably needs further investigation / validation.  I suppose that a Z coordinate could be associated with every point on a polyline/span.

**Comment by duncandewhurst** [comment]
> I suppose that a Z coordinate could be associated with every point on a polyline/span.

Indeed, and that is already supported in the standard, albeit not really mentioned in the docs. So I think the question is whether the status quo (mostly undocumented support) is acceptable; whether to add some documentation to explain how to express 3D span routes using the existing data model; or whether to add a span-level depth field so that publishers can express deployment depth without needing to specify Z coordinates for every point in a span.

**Comment by stevesong** [comment]
Or perhaps even at the phase level as deployments would likely have a depth / quality of deployment written into the construction contract.  I think this is an issue that merits further consultation with operators and regulators and thus not something to directly address in the .4 release.

**Comment by duncandewhurst** [comment]
Sounds good! I'll set its priority to "won't have" (this time).

**Comment by duncandewhurst** [comment]
In the ArcGIS Communications System data model (see #347), the `conduit` class has a numeric `depth` attribute.
