### ISSUE TITLE
Fibre sub-types

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#121]
This point was raised as part of our [Alpha consultation](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/115):

> the fiberType only lists the major standards and not the sub-standards. For example, it lists G.652. However, G.652 has four sub-types (A, B, C, and D). Without the sub-types, you can't tell if the fiber is suitable for some technologies. G.652.A and G.652.B have significant losses due to water peaks whereas G.652.C and G.652.D do not. This is less of an issue with some of the other types such as G.655, however, it is informative to know the specific fiber type and not just the general fiber type.

At present the sub-type could be recorded in the free text `link.fibreTypeDetails` field. We should consider whether to model this explicitly.

**Comment by lgs85** [comment]
As far as I can tell, there isn't a single, definitive, list of fibre sub-types below the level outlined in the ITU-T recommendations [here](https://www.itu.int/rec/T-REC-G/en). Sub-categories are mentioned within the individual pdf files that contain the recommendations (e.g. [this file for the G.652 recommendation](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-G.652-201611-I!!PDF-E&type=items)), but not in a way in which I can see that it would be possible to maintain an up-to-date codelist at the subtype level. If anybody is aware of such a list that I've missed, please do let me know!

Nonetheless, we need to allow subtypes to be specified, even the absence of a subtype codelist. A proposed solution to this is to add a `fibreSubtype` field to the `fibreTypeDetails` object. This will be a character field with the following definition:

> The sub-category of the fibre type. For example, G.652.B.

We will also keep `fibreTypeDetails.description`, where further details about the fibreType can be added.

**Comment by duncandewhurst** [comment]
The person who raised the original feedback confirmed that they are happy with the proposed approach. They also confirmed that there is no definitive list of fibre sub-types and that they are only relevant for some fibre types.
