### ISSUE TITLE
Create visualisation tool

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#124]
We'd like to have a tool that visualises OFDS data on a map linked to the validation and conversion tooling. In the first instance this can be a simple visualisation that takes OFDS data in one or more of the supported formats an input. Some decisions that we'll need to make include:

- Should this be part of the validation tool or a standalone tool?
- What formats should this tool support and how should we deal with conversion?
- How much additional data beyond the coordinates do we want to visualise in the initial release?

**Comment by duncandewhurst** [comment]
Continued in https://github.com/Open-Telecoms-Data/cove-ofds/issues/6

**Comment by duncandewhurst** [comment]
Closing as this is done in CoVE.
