### ISSUE TITLE
Add guidance on location obfuscation to address concerns about disclosing detailed location data

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#133]
From https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/37#issuecomment-1254263157

> Something else to add is guidance on location obfuscation to address concerns about disclosing detailed location data.

**Comment by stevesong** [comment]
What we have discussed in the past, is using decimal precision in Lat/Long as a proxy for obfuscation.   The question would be what minimum level of accuracy is sufficient to meet an Open Fibre Data standard.  Something like 4 decimal places i.e. 11m would be sufficient for public data IMO.  But open to discussion.

0.001° 	        ± 111 m
0.0001°    	± 11.1 m
0.00001° 	± 1.11 m
0.000001° 	± 0.111 m

**Comment by duncandewhurst** [comment]
Yes, those were the lines I was thinking along. I'm not sure we need to define a particular level as different implementers may be comfortable with different levels of accuracy. However, we can certainly provide guidance on using decimal precision in Lat/Long as a proxy for obfuscation.
