### ISSUE TITLE
Related resources bug in reference page

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#137]
In the reference page [table of top-level fields](https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#structure) there is an entry for `relatedResources`, and also entries for `relatedResources/0/href` and `relatedResources/0/rel`. These latter two entries should be removed.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/180
