### ISSUE TITLE
Decide whether to use Flatterer or Flatten Tool for converting from JSON to CSV format

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#14]
We need to decide whether to use [Flatterer](https://flatterer.opendata.coop/) or [Flatten Tool](https://flatten-tool.readthedocs.io/en/latest/) for converting from JSON to CSV format.

Some things to consider:

* Is converting from spreadsheet/CSV format to JSON relevant?
* Suitability for use in publication pipelines.
* (Possibly) ease of adding special casing: https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/10

**Comment by stevesong** [comment]
The number one question for me is what is the CSV use case?  Perhaps if the records are capturing the kilometre length of links, it would be useful to open in a spreadsheet.  Other scenarios?

**Comment by duncandewhurst** [comment]
Good question. Tabular data was the only publication format preference expressed in the stakeholder interviews, but we didn't hear about specific use cases for it. The opinions expressed were that publishing and using data on nodes and links (without detailed routes of links) would be most straightforward in a tabular format. The supply side research also surfaced several examples of tabular publications so a tabular format may be more familiar/achievable for some publishers.

That said, many of the use cases identified in the demand side research were concerned with the detailed routes of links, for which JSON/GeoJSON seems better suited.

In general, if the only formats are JSON/GeoJSON, then users interested only in non-spatial data elements (like link length, investors, status and dates of phases etc.) would need to be skilled in processing JSON data or would need to load the data into a GIS tool to do anything with it, which is a potential barrier to use. CSV data is much easier to work with for users who are only skilled in using spreadsheets or databases.

**Comment by lgs85** [comment]
Noting here that this is also dependent on any decision made in #17.

**Comment by duncandewhurst** [comment]
@kindly if we were to use Flatterer's output as the CSV format for OFDS data, how much work would it be to author a conversion script so that CSV data could be converted to JSON format for validation in CoVE?

If it's a lot of work, could we instead use Flatterer to generate a `datapackage.csv` that could be used to validate CSV data using [`frictionless`](https://pypi.org/project/frictionless/)?

**Comment by kindly** [comment]
@duncandewhurst flatterer is really intended for just flattening as it creates `_link` fields to express the join conditions and those link fields would be diffucult to create by hand.

Nonetheless recently flatterer has a feature called `pushdown` which can copy all `id` fields to the child one-to-many relationships and it prefixes those `id` fields with the table where they originated. This is similar to the id_field feature in flattentool.  Using this feature I think it would be possible to do the unflattening in a script or potentially convert the headings to ones that flatten-tool expects.  I have not thought about this deeply though so I am not 100% sure how feesable this.

**Comment by duncandewhurst** [comment]
Thanks, @kindly 

Would using a data package schema be an alternative to unflattering for CSV validation?

> If it's a lot of work, could we instead use Flatterer to generate a `datapackage.csv` that could be used to validate CSV data using [`frictionless`](https://pypi.org/project/frictionless/)?

**Comment by duncandewhurst** [comment]
For the Alpha at least, we've decided to use Flatten Tool because it offers support for round-tripping and has better organisational support. I've opened an issue about support for streaming in Flatten Tool: https://github.com/OpenDataServices/flatten-tool/issues/399

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
