### ISSUE TITLE
Add a script to update the organisationIdentifierScheme codelist

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#150]
Add a script to download the CSV file from http://org-id.guide/download.csv and extract the relevant columns:

- code
- name/en (title)
- description

**Comment by duncandewhurst** [comment]
#158 adds the CSV file. The outstanding task is to author a script to update it.

**Comment by ghost** [comment]
This still means that if a new org-id code is added, it won't be available in the schema till the script is run and file updated. Is it interesting to look into ways we can mark the schema as using these options and then cove and other tools downloads the list regularly? I think (from memory) another Cove does this.

(Sorry for dupe, did search, just not well enought!)

**Comment by duncandewhurst** [comment]
I'm not too worried since it is an open codelist, but it could be something to look at in the future.

**Comment by duncandewhurst** [comment]
Closing in favour of https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/95
