### ISSUE TITLE
Broken link to linkRelationType codelist.

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/open-fibre-data-standard#156]
https://open-fibre-data-standard.readthedocs.io/en/0.1-dev/reference/schema.html#browser

Find "links" bit.

Link to codelist in rel field

Problem is it links to "latest" version of docs maybe?

This linking problem will apply to all links in JSON Schema I guess. (Don't just make them relative links, we have had issues with that elsewhere)

**Comment by duncandewhurst** [comment]
Yep, links in schema descriptions on dev branches may be broken until #153 is done

**Comment by duncandewhurst** [comment]
Closing in favour of https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/153
