### ISSUE TITLE
Decide how to specify the GeoJSON format

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#16]
The [data stewardship, publication formats and access methods consultation paper](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/3) sets out 3 publication formats to meet a range of use cases:

* JSON
* GeoJSON
* CSV

The single source of truth for the data model will be the JSON schema for the JSON publication format

We need to decide how to specify the GeoJSON publication format. I think we have two options:

1. Use a script to generate a schema for the GeoJSON format format, based on the schema for the JSON format.
2. Rather than maintaining a separate schema for the GeoJSON format, document a set of rules for converting from the JSON format to the GeoJSON format and provide a reference implementation (see https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/15), similar to the [merging routine in OCDS](https://standard.open-contracting.org/latest/en/schema/merging/#merge-routine).

Things to consider:

* Do we need to provide support for validating data in GeoJSON format or is it sufficient to validate data in JSON format and use a conversion tool (see https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/15) to generate data in GeoJSON format
* How to keep the documentation approachable for implementers. Having multiple schemas might be confusing.

**Comment by lgs85** [comment]
My initial thoughts on this are that separate JSON and GeoJSON schemas would be confusing for users, given the similarity of the two formats, and therefore that option 2 is more sensible.

If any tooling we provide converts both from JSON to GeoJSON and back (which would be simple enough), I think this would negate any need to provide support for validating GeoJSON data?

**Comment by duncandewhurst** [comment]
> If any tooling we provide converts both from JSON to GeoJSON and back (which would be simple enough), I think this would negate any need to provide support for validating GeoJSON data?

Yes, that seems like a sensible approach. I haven't thought about it in detail, but, since the GeoJSON would repeat some network and phase-level information for each feature, the conversion tool would need to handle the possibility of inconsistent information. However, it could simply issue a warning in that case. Similar to how CoVE issues warnings when there are issues converting spreadsheet data to JSON format for validation.
