### ISSUE TITLE
Remove Python code that is available in external libraries

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#170]
Originally posted by @odscjames in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/19#issuecomment-1294600302:
      
> [remove] Python **checking** but to removing actual bits of Python **code**, if that code is now available in external libraries like ofdskit instead (and of course ofdskit does have Python checking!)

**Comment by ghost** [comment]
The convert_to_geojson command can be removed from manage.py, I think?
