### ISSUE TITLE
GeoJSON -> JSON: Shift the specification into a table for easier reading/reference

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/open-fibre-data-standard#175]
From https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/25

> Shift the specification into a table for easier reading/reference (@duncandewhurst will do)

(FWIW, I didn't find a lack of table hard to deal with here.)

**Comment by duncandewhurst** [comment]
I'm going to close this issue because I don't think there's a clear need to do this.
