### ISSUE TITLE
Decide whether to have separate files for links and nodes in the GeoJSON format

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#18]
The data stewardship, publication formats and access methods [consultation paper](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/3) provides examples of what the JSON and GeoJSON publication formats might look like.

In the GeoJSON example, nodes and links are grouped together into a single `FeatureCollection`.

There are a couple of issues with this approach:

* There's no way of readily distinguishing which features are nodes and which are links, which might be an issue for users, and would also make conversion from GeoJSON to JSON difficult
* If node and link identifiers in the JSON representation are only unique within the `nodes` and `links` arrays respectively, then once they are all grouped together into a feature collection, there might be clashing ids.

Separate feature collections (files) for nodes and links might be the solution to this.

**Comment by lgs85** [comment]
Just to fully explore the discussion, and appreciate that I'm coming to this late... I'm assuming that combining nodes and links into a single 'element/feature/component' object is off the cards? This would allow an element type of node/link to be defined, but would complicate the schema in other ways. 

If we agree this isn't workable, then I agree that separate files is the best (only) solution.

**Comment by duncandewhurst** [comment]
A couple of reasons for having separate classes:

* I think that nodes and links have more differences than commonalities so it wouldn't make sense to represent them using the same class.
* In the supply side research, we found that nodes and links were often published as separate datasets or layers, so I think it would be confusing for publishers and users to represent them using the same class.

**Comment by duncandewhurst** [comment]
Since we don't have another option on the table, we'll use separate files for the alpha.
