### ISSUE TITLE
Consider adding service providers to spans

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#195]
The [service layer of the network value chain](https://open-fibre-data-standard.readthedocs.io/en/latest/primer/scopeandkeyconcepts.html#the-network-value-chain) is out of scope for OFDS. However, service providers may in some instances be able to provide information about the active and passive infrastructure layers that might not otherwise be declared. For example, in a scenario where company A leases lit capacity from company B, and company A wishes to publish information about their network while company B hasn't yet got round to it, company A may be discouraged from using the standard.

In a similar vein, operators may possess single datasets about their entire network, including parts where they only operate as a service provider. Excluding this role would create extra work in the publishing process in such instances, or publishers may incorrectly use an existing role type.

An optional `serviceProvider` object at the span level, and an accompanying addition to the `roleType` codelist would address the above issues. However, this would introduce some ambiguity about the scope of the standard, so requires some thought.

**Comment by duncandewhurst** [comment]
> For example, in a scenario where company A leases lit capacity from company B, and company A wishes to publish information about their network while company B hasn't yet got round to it, company A may be discouraged from using the standard.

It would be good to unpick this scenario a bit more. The definition of network provider in OFDS allows for leasing active network infrastructure:

> An organisation that operates the active network infrastructure, i.e. the electrical elements, such as optical transceivers, switches and routers. In open business models, network providers provide wholesale access to service providers such as retail internet service providers. **Network providers can own or lease the active network infrastructure.**

**Comment by lgs85** [comment]
The more I think about this, the more I think that adding this in wouldn't be helpful at this stage. Closing for now.
