### ISSUE TITLE
Add a link to CoVE in the sidebar

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#198]
Once https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/196 is merged, there will be a link to CoVE in the publication guidance. We should add a link to the sidebar so that it is more discoverable.

We can likely use a similar to approach OCDS's [`layout.html`](https://github.com/open-contracting/standard/blob/1.2-dev/docs/_templates/layout.html).

**Comment by duncandewhurst** [comment]
The link can appear after the TOC in the sidebar. I think that the text should be 'Convert, Validate and Explore your data'.

**Comment by Bjwebb** [comment]
The easiest thing to do is to add it without extra spacing: https://open-fibre-data-standard.readthedocs.io/en/nav-link-cove/

Or, do you want extra spacing like OCDS? https://standard.open-contracting.org/latest/en/

**Comment by duncandewhurst** [comment]
Without extra spacing is fine. 

Looking at the preview, I would like to make a few tweaks:

1. I think the text should be 'Convert, Validate and Expore Tool' to better signal that the link leads to a tool, rather than a documentation page.
2. The link should open in a new tab/window.
3. To distinguish it from the other menu items, would it be possible to add an external link icon like the one below?

![image](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/assets/19265814/46a14774-91eb-4005-baa8-7ad0c9162774)

Thanks!

**Comment by Bjwebb** [comment]
I've made all those changes, how does this look: https://open-fibre-data-standard.readthedocs.io/en/198-nav-link-cove/

**Comment by duncandewhurst** [comment]
Perfect! Thank you :-)
