### ISSUE TITLE
Order codes in codelists

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#209]
We should check that codes in each codelist are ordered logically. For example, in the [nodeStatus codelist](https://open-fibre-data-standard.readthedocs.io/en/latest/reference/codelists.html#nodestatus), it would make sense for 'inactive' to appear between 'underConstruction' and 'operational', rather than at the end of the list.

For most codelists, I think alphabetical order is fine, but we can use this issue to agree the appropriate order for each codelist.

**Comment by odscjen** [comment]
The following are alphabetical and I'm suggesting it's fine to leave them that way
* contractType
* language
* linkRelationType
* mediaType
* organisationIdentifierScheme
* country
* currency
* deployment
* fibreType
* geometryType

The following aren't alphabetical but I'm suggesting they should be:
* nodeTechnologies
* nodeType
* spanTechnologies
* transmissionMedium

All others:
codelist | current order | suggested order
-- | -- | --
organisationRole | primacy of "ownership": infra provider, network provider, funder, supplier | keep as is
nodeStatus | mostly temporal order in which the status occurs in lifetime of a node but with inactive at the end | reorder: proposed, planned, underConstruction, inactive, operational, decommissioned
spanStatus | no clear order | change to temporal order same as suggested order for nodeStatus

@stevesong are you happy with these proposed orderings in the codelists?

**Comment by stevesong** [comment]
That all makes sense to me.
