### ISSUE TITLE
make autobuild: rebuild on changes outside the docs folder

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#21]
The OCDS docs have a really nice `make autobuild` command (mentioned [here](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/build.html)) that:

* builds the docs
* opens the built docs in a browser
* watches the source files and rebuilds on changes
* refreshes the browser

This really speeds up standard development because, once run, you can preview your changes locally without needing to run any further commands in the terminal.

@lgs85 if you're familiar with make files, would you be up for trying to set this up? If not, perhaps a developer could look at it as part of https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/19

**Comment by lgs85** [comment]
this should be working now in #20 and have added some basic documentation in a [PR](https://github.com/Open-Telecoms-Data/standard-development-handbook/pull/8) on the handbook repo

**Comment by duncandewhurst** [comment]
@lgs85 not urgent, but can this be updated to detect and rebuild on changes outside the docs folder, e.g. changes to the schema or example files?

**Comment by duncandewhurst** [comment]
@lgs85 in OCDS, the makefile is in the root of the repository, rather than in the docs folder and the `common.mk` file that it references [doesn't use the -E flag](https://github.com/open-contracting/standard/blob/86b675e7b4380025d1569278693e371426efd467/include/common.mk#L124). Could that be an option?
