### ISSUE TITLE
Remove Github issue admonitions

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/open-fibre-data-standard#222]
We've seen the precommit hook change the docs - it has the same github issues, but they appear in a different order.

We should add something to manage.py to order the issues by something to make sure we get stable builds and to keep random noise out of commits.

Found when doing #19

**Comment by duncandewhurst** [comment]
We're no longer linking GitHub issues to fields in the schema so we should remove those admonitions as they'll become staler and staler. I've updated the issue title accordingly.
