### ISSUE TITLE
Github Actions/Tests/Precommit: Capitalise all Codelist CSV file headers?

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/open-fibre-data-standard#227]
One of the things done in #166 is to Capitalise all Codelist CSV file headers but there is no corresponding test for that - do we want one? Or might there be possible exceptions in the future?

Split out from https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/19

**Comment by duncandewhurst** [comment]
I'm happy with capitalised headers. In #166 we started to add a schema for testing codelists. If there are exceptions in the future we can handle that either in the schema or the tests that use it.

**Comment by ghost** [comment]
For reference that is https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/ded3cb39d35ced8d41388adf32fe8be48831f061/schema/codelist-schema.json

Commits
* https://github.com/Open-Telecoms-Data/open-fibre-data-standard/commit/0844712c8e211a42156b0796d1758981eae29d62
* https://github.com/Open-Telecoms-Data/open-fibre-data-standard/commit/e0d05f3efcd5f437a25c581c30beeee26d206d25

However I can't find anything in #166 that actually uses that schema to test the code lists - is that still to be written or am I missing something?

**Comment by duncandewhurst** [comment]
> However I can't find anything in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/166 that actually uses that schema to test the code lists - is that still to be written or am I missing something?

I don't know. @Lathrisk could you confirm where you got up to please?

**Comment by Lathrisk** [comment]
@duncandewhurst @odscjames 
I had added a draft schema, but not any associated tests when James took over this work. I planned to use the [equivalent test](https://github.com/open-contracting/standard-maintenance-scripts/blob/459008386155ac6db1f06ab3ef2876456c801745/tests/test_csv.py#L98) elsewhere as a base.

**Comment by ghost** [comment]
Think this is now done?

**Comment by duncandewhurst** [comment]
Yep!
