### ISSUE TITLE
manage.py: unknown url type error

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#237]
The `pre-commit` command of in `manage.py` is now resulting in the following error:

>Error while resolving `#/definitions/Node`: ValueError: unknown url type: ''

@odscjames has pinpointed this to [this commit](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/commit/0ed09b0b0399d7a5ab8627d29941a6ac1f9dcfcd), and closer inspection shows that this is the result of specifying `include_definitions = False` in [this ocdskit function](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/manage.py#L458). I'm not familiar with `mapping_sheet` but can take a closer look at what's going on, unless someone else has an immediate answer.

**Comment by duncandewhurst** [comment]
Need to update requirements.txt to latest version of OCDS Kit
