### ISSUE TITLE
Declare the documentation mode of each markdown page

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#248]
From https://github.com/evildmp/diataxis-documentation-framework/discussions/26:

> The intention would be to hint to editors which type of documentation the page is aiming to be, so that they don't inadvertently start adding explanation to a reference page.

**Comment by odscjen** [comment]
All files in the docs/ folder:

file(s) | doc type
-- | --
reference/ | reference
history/ | reference
support/index.md | reference
primer/ | explanation
guidance/ | how-to-guides
index.md | explanation
governance | reference
