### ISSUE TITLE
Link deployment

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#26]
Based on the [supply side research](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/5), most datasets categorise the deployment of a link as either underground or aerial. However, some datasets feature links with mixed deployment, i.e. underground and aerial. Some datasets also provide more detailed classifications of deployment, some of which do not fit a simple underground or aerial classification:

| Deployment | Underground or aerial | Reference |
| -- | -- | -- |
| skywrap_aerial | Aerial | [SkyWrap – attached optical cable for aerial power lines](https://www.aflglobal.com/en/Products/Fiber-Optic-Cable/Aerial/Skywrap#sort=date%20descending) |
| OPGW_aerial | Aerial | [Optical ground wire - Wikipedia](https://en.wikipedia.org/wiki/Optical_ground_wire) |
| All Dielectric Self Supporting aerial | Aerial | [AFL-ADSS® (All-Dielectric Self-Supporting) fiber optic cable is a non-metallic cable which supports its own weight without the use of lashing wires or messenger cables.](https://www.aflglobal.com/en/Products/Fiber-Optic-Cable/Aerial/ADSS#sort=date%20descending) |
| against wall | ? | |
| roof | ? | |
| sewer | Underground | |
| trench | Underground | |
| indoor | ? | |
| outdoor | ? | |
| overhead | Aerial | |
| dropwire | Aerial | [BT Drop Wire - FS Cables](https://www.fscables.com/products/bt-drop-wire.html) |
| HDD | Underground | [What is HDD? Trenchless Boring for Underground Cables...](https://www.hddrilling.co.za/what-is-horizontal-directional-trenchless-drilling) |
| inside building | ? | |

Based on the above, the following modelling seems appropriate:

* A `Link.deployment` string array with a short closed codelist.
* A `Link.deploymentDetails.description` field for publishers to provide further details.
* A `Link.deploymentDetails` object to provide for additional properties in the future.

For the codelist, I think we have two options:

1. Underground and aerial. This is most closely aligned with the terminology we've seen in the supply side research, but would mean that it isn't possible to map some of the examples above.
2. Replace 'aerial' with 'aboveGround' to cover the other cases in the table above. If we do that, we should probably also replace 'underground' with 'belowGround' for consistency.

I prefer option 2. as it would result in greater coverage but I would like to hear feedback on whether this would cause any issues for users.

**Example**

```json
{
   "links": [
    {
      "deployment": ["belowGround"],
      "deploymentDetails": {
        "description": "Trench"
      }
    },
    {
      "deployment": ["aboveGround"],
      "deploymentDetails": {
        "description": "OPGW"
      }
    },
    {
      "deployment": ["aboveGround", "belowGround"]
    }
  ]
}
```

**Comment by lgs85** [comment]
Going with Duncan's suggestion of an array from a codelist containing `aboveGround` and `belowGround`, alongside a `deploymentDetails` object.

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflect option 2 in the proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
