### ISSUE TITLE
Consider language around 'use cases'

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#28]
Throughout the documentation (e.g. in the [landing page](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/index.md)) we should consider using different language to 'use cases'. Users/stakeholde needs may are possible options.

**Comment by duncandewhurst** [comment]
I'm going to close this issue because the [why publish open fibre data](https://open-fibre-data-standard.readthedocs.io/en/latest/primer/openfibredata.html#why-publish-open-fibre-data) section of the primer introduces alternative terms (stakeholders, purposes).
