### ISSUE TITLE
Provide definitions for key terms

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#29]
On the primer page on [open fibre data](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/primer/openfibredata.md) we should consider providing definitions for key terms, either in a tooltip or by linking to them

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/68
