### ISSUE TITLE
Consider alternative terms for 'administrative data'

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#30]
In the primer page on [open fibre data](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/primer/openfibredata.md) we use the term 'administrative data' to cover data such as the organisations that own passive infrastructure or operate active network infrastructure. We should consider whether there are alternative terms that might better describe this data.

**Comment by duncandewhurst** [comment]
I'm going to close this issue as the supply and demand side research did not surface any particular alternatives.
