### ISSUE TITLE
Check and update scope and concepts terminology and definitions

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#34]
In the primer documentation on [scope and key concepts](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/primer/scopeandkeyconcepts.md), terminology and definitions need to be checked and updated throughout. We should also consider whether we can link definitions to the schema.

**Comment by duncandewhurst** [comment]
In particular, we'll need to update the definition and explanatory text for `Link`.
