### ISSUE TITLE
Consider whether to expand the definition of a link

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#36]
In the primer documentation on [scope and key concepts](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/primer/scopeandkeyconcepts.md) we say that:

> Links can be either direct physical connections between nodes, for example in granular data about an access network, or abstract connections between nodes, for example in less granular data about a national backbone network

We should consider whether to add this to the definition of a link.

**Comment by duncandewhurst** [comment]
I don't think the concept of an abstract connection here is helpful. I've removed it from the schema definition and the primer.
