### ISSUE TITLE
Draft guidance section of documentation

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#37]
The [guidance](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/guidance.md) section of the documentation needs to be written. Initial suggested headings are:

- Data publication
    - How to format data for publication
    - How to provide access to data
    - How to add additional fields
    - How to write a data user guide
- Data use
    - How to find data
    - How to access data
    - How to create maps
    - Joining links to nodes
    - How to analyse data

**Comment by duncandewhurst** [comment]
When authoring the data publication guidance, we should make reference to the W3C's [Data on the Web Best Practices](https://www.w3.org/TR/dwbp/) and [Spatial Data on the Web Best Practices](https://www.w3.org/TR/sdw-bp/.

**Comment by duncandewhurst** [comment]
Another topic for data publication guidance is layering networks with different physical infrastructure and network providers.

We can use this map from Nigeria as an example:

![image](https://user-images.githubusercontent.com/19265814/189244902-ed8a705a-4ab6-477a-ad55-17be5ccda3e2.png)

**Comment by duncandewhurst** [comment]
> How to format data for publication

This section should cover appropriate size limits for API responses and bulk files. It is linked from the descriptions of `.nodes` and `.links`.

**Comment by duncandewhurst** [comment]
Draft remaining publication guidance. Move empty headings to issues.

**Comment by lgs85** [comment]
One thing you might want to consider once you have draft sections is the section order. I think that moving the publication formats section to the top might make the whole structure more logical.

**Comment by lgs85** [comment]
Adding as a note that at some point it would be good to think about what more detailed guidance for converting to OFDS might look like.

**Comment by duncandewhurst** [comment]
Something else to add is guidance on location obfuscation to address concerns about disclosing detailed location data.

**Comment by duncandewhurst** [comment]
I've created separate issues for the various suggestions in this issue so that we can prioritise them individually.
