### ISSUE TITLE
more detail in the "announcement" post

### ISSUE THREAD

**Issue by stevesong** [Open-Telecoms-Data/open-fibre-data-standard#41]
It would be great to have one url that has links to the consultation docs and associated discussions.  When pointing someone to this repository, there is no one page that does that.  That could potentially be in the [announcement post ](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/2) in the discussion area or perhaps in the Readme for the repo

**Comment by lgs85** [comment]
Good idea. Now added to the [announcement post](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions/2). Please do re-open if I've missed anything.
