### ISSUE TITLE
Draft primer section on Geo data

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#42]
In the primer section on [scope and key concepts](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/docs/primer/scopeandkeyconcepts.md) the section on Geo data needs to be drafted.

**Comment by lgs85** [comment]
I can have a go at this. @duncandewhurst did you already have something in mind with regards to content? In keeping with this being in the primer, I'd imagine we'd want to keep it very brief, and cover:
- A definition of geospatial data
- Open Fibre data as geospatial data
- Something very brief about formats, with (possibly) a very short [GeoJSON example](https://docs.google.com/document/d/1ZDx69xTU7fjGP-6WRYV2FpGreGRk4JQlpkubObf6q2c/edit#heading=h.2bgwl1aduar1)

Anything else?

**Comment by duncandewhurst** [comment]
That sounds good to me. We might identify some additional content to include in the primer when we come to draft the guidance on publishing and using data, or through learnings from the pilots, but that's not a blocker to drafting a section based on your proposal.
