### ISSUE TITLE
Adopt a consistent terminology for geodata/geospatial data/geographical data/spatial data

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#48]
A minor one, but geographical data is often referred to interchangeably in all of the above ways. To make our documentation more readable, we should pick a term, define it and use throughout. At present we are predominantly refer to 'Geo data' and 'geodata', though we also use 'spatial data'.

The [IETF](https://www.rfc-editor.org/rfc/rfc7946) refer to GeoJSON as 'geospatial data', so we may want to use that, but I don't mind what we go with.

Once decided we can also update the relevant section of the [handbook](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/common_conventions.html#word-choice).

Relates to #42

**Comment by duncandewhurst** [comment]
+1 to geospatial data. Happy for you to make those changes!
