### ISSUE TITLE
Can we configure ReadtheDocs to build branches?

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#52]
Currently, ReadtheDocs only builds one version (latest). Can we configure it to build development branches too so that staging/preview versions are available online?

I don't think we would want these to be available in the version switcher in the built docs. It would be sufficient to access them at https://open-fibre-data-standard.readthedocs.io/en/<branch-name>/

**Comment by lgs85** [comment]
Yes I can take a look at this next week.

**Comment by lgs85** [comment]
Now done - I've set up 2 automation rules in readthedocs, to i) build, activate and hide new branches, and ii) delete versions on branch deletion. Making them hidden means that they don't come up in the flyout menu but you can access them via the url. e.g:

https://open-fibre-data-standard.readthedocs.io/en/42-draft-primer-section-on-geo-data/primer/scopeandkeyconcepts.html

I'll add a line to the handbook describing this.
