### ISSUE TITLE
What spelling standard should we use?

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#54]
The draft data model and documentation use British English, based on the ITU's spelling of 'fibre'. However, I see that the ITU actually uses [Oxford spelling](https://en.wikipedia.org/wiki/Oxford_spelling), which prescribes the use of British spelling in combination with the suffix -ize in words like realize and organization. Another option is to use American English, which is used by the World Bank. Which spelling standard should we use?

**Comment by duncandewhurst** [comment]
@stevesong we've not had any feedback on this issue. Are you happy for it to be closed and for the standard to use British English?

If there's a chance that might be a problem, it is important to address it before implementations take place since changing to another spelling standard could lead to some field names changing (e.g. `organisations`), which would be a breaking change for implementers and users.

**Comment by stevesong** [comment]
Given that there doesn't seem to be a middle ground option and the fact that we are focused on the African region to begin with, where UK English spelling is more prevalent than US, I am ok with closing this.  However, I do think we be a little bit proactive on this. Is there any way that we might build some checking on this into the validation tools?  Looking for obvious keywords like 'fibre', 'organisation', etc.?

**Comment by lgs85** [comment]
@stevesong I think that this is a good shout, and have [added a suggestion](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/1#issuecomment-1280888386) to the validation tool repo
