### ISSUE TITLE
Node definition (access points)

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#60]
The draft description of [Node](https://airtable.com/apprMa4GXD05csfkW/tblRv51cg2Apmyopl/viwWLwKBkhZ0BvrQL/recRbHSN95YZYL44K?blocks=hide) defines a node as an access point:

> An access (entry or exit) point to a network. A node consists of active or passive equipment that is capable of providing access to the network. Sites at which there are no means of access to a network are not classified as nodes. Nodes can allow for interconnections to other networks, and/or connections to end users.

This definition is based on indicator 2 from the [ITU Broadband Transmission Capacity Indicators](https://drive.google.com/file/d/10FF88uaYEu98v5xPawkaeNXvhKz_1162/view).

When we presented the conceptual model, @stevesong said that when a network forks, it doesn’t necessarily provide access to the network but it’s still important to draw the network well.

To address that concern, we could pair a broader definition of `Node` with a boolean `Node.accessPoint` field:

> `Node`
> A point within a network. A node may be an access point or may reflect a geographic point at which a link splits, aggregates or crosses a border. Nodes can allow for interconnections to other networks or connections to end users.
> `Node.accessPoint`
> Whether transmission equipment is installed at this node which is capable of providing access to the network.

This approach would also allow for repeater sites to be represented as nodes, which is something that we saw in the supply side research.

However, I'm a little unclear on what exactly 'access to the network' means. The ITU's indicator equates access points with [add/drop multiplexers](https://en.wikipedia.org/wiki/Add-drop_multiplexer):

> A node is an access (entry or exit) point to a transmission network. In a fibre optic transmission network, a node is an add/drop (drop/insert) point.

But I don't know, for example, if that excludes the splitters used in a [GPON FTTH access network](https://community.fs.com/blog/components-and-architecture-of-gpon-ftth-access-network.html).

@stevesong it would be great to get your feedback on this.

**Comment by stevesong** [comment]
I like the proposed solution of the broader definition with an Node.accessPoint being a subset of the larger category of Node.  It would be good to have Dale Smith of NSRC (member of the technical working group) weigh in here as well.  I'll ping him.

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflect the latest proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
