### ISSUE TITLE
Pre-release versioning

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#63]
We need to decide on the version numbers for the pre-release. We'd like to follow [semantic versioning](https://semver.org/), so I think it would make sense to aim for 0.1.0-alpha for the initial pre-release. This issue is to explore alternatives.

**Comment by duncandewhurst** [comment]
+1 to 0.1.0-alpha for the first version.

**Comment by duncandewhurst** [comment]
Mostly done in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 but version number in `conf.py` needs updating.

**Comment by lgs85** [comment]
Closed with #101
