### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#70]
GIS analysts need to know the positional accuracy of coordinates so that they can account for it in their analysis.

The supply side research surfaced examples of very granular data on access networks, in which the coordinates identified individual streets and buildings, and very high-level data on national backbone networks, in which coordinates identified only the town or city in which the node was located.

Different jurisdictions use different methods for calculating and reporting coordinate accuracy, e.g.
* [Australia - Map and Spatial Data Horizontal Accuracy Standard](https://www.icsm.gov.au/sites/default/files/Spatial_Data_Horizontal_Accuracy.pdf)
* [EC Land Parcel Identification System - Positional Accuracy](https://marswiki.jrc.ec.europa.eu/wikicap/index.php/Positional_Accuracy)
* [New Zealand - Standard for the geospatial accuracy framework](https://www.linz.govt.nz/system/files_force/media/regulatory-documents/25005-Standard%20for%20the%20geospatial%20accuracy%20framework%20-%20LINZS25005_4.pdf?download=1)

Given that different publishers are likely to use different approaches, I don't think that the standard should specify a particular method as that might require publishers to carry out new measurements and calculations in order to publish OFDS data.

The above methods distinguish between:

* Absolute (or network) accuracy, i.e. a value that represents the uncertainty of a coordinate relative to a datum; and
* Relative (or local) accuracy, i.e. a value that represents the uncertainty of a coordinate relative to other coordinates nearby.

My understanding is that absolute accuracy is the most relevant figure for describing the accuracy of coordinates in OFDS data.

Ultimately, the above methods can all be reported in metres although the figures will not necessarily be comparable.

The W3C's Spatial Data on the Web Best Practices recommends [describing the positional accuracy of spatial data in both human readable and machine-readable form](https://www.w3.org/TR/sdw-bp/#desc-accuracy).

**Proposal**

Provide two fields that can be used to represent the accuracy of coordinates in an OFDS dataset:

* `accuracy`: The horizontal uncertainty, in metres, of the coordinates in this dataset relative to the datum of the coordinate reference system specified in `crs`.
* `accuracyDetails`: Further details about the accuracy specified in `accuracy`. For example, the confidence level of the accuracy measurement, the methodology used to calculate the accuracy, or a local classification of accuracy.

**Comment by lgs85** [comment]
Agree with the above proposal

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflect the latest proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
