### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#71]
The [draft data model](https://drive.google.com/file/d/1Z4QlhrXv6WGBPF6Qgt-EdWSvjdaATMnn/view) proposed by the technical working group includes the following fields related to contracts:

![image](https://user-images.githubusercontent.com/19265814/188545490-76ccd168-540c-454e-85fc-f15dc73b1d37.png)
![image](https://user-images.githubusercontent.com/19265814/188545502-1045b71a-756c-4e10-93aa-4abbc1565196.png)
![image](https://user-images.githubusercontent.com/19265814/188545506-80c1bd8a-44e2-4987-ad8a-1d3075e30758.png)

The supply side research did not surface any examples of structured data on contracts nor did the demand side research surface any specific demands for this data. Presumably, these fields were proposed for a reason and the supply side research did surface examples of publication of contract documents ([New Zealand](https://www.crowninfrastructure.govt.nz/fibre/ufb-programme/)) and contract summaries ([UK](https://www.gov.uk/guidance/project-gigabit-network-build-contract-north-dorset)), so we should not omit contract related fields from the data model entirely and we should ensure that multiple documents can be linked for each contract.

**Proposal**

Add a `contracts` property to `Network` and reuse the following properties from the Open Contracting Data Standard's  [`Contract`](https://standard.open-contracting.org/latest/en/schema/reference/#contract):

* `id`
* `title`
* `description`
* `value`
* `dateSigned`
* `documents`

Add a `Contract.type` property with a codelist based on the World Bank Public-Private Partnership Legal Resource Centre's [categorisation of contract types](https://ppp.worldbank.org/public-private-partnership/ppp-contract-types-and-terminology) as public, private or public-private partnership.

Add a `Contract.relatedPhase` property to link contracts to phases.

**Example**

```json
{
  "contracts": [
    {
      "id": "1",
      "title": "Network Infrastructure Project Agreement",
      "description": "Contractual arrangement between Crown Infrastructure Partners and Chorus for the delivery of UFB. This agreement was signed prior to the demerger of Chorus and Telecom (1 December 2011), therefore Telecom is the signatory.",
      "type": "ppp",
      "relatedPhase": "1",
      "documents": [
        {
          "id": "1",
          "title": "Network Infrastructure Project Agreement",
          "url": "https://www.crowninfrastructure.govt.nz/wp-content/uploads/2018/07/Network-Infrastructure-Project-Agreement-NIPA-24-May-2011.pdf"
        },
        {
          "id": "2",
          "title": "Fact sheet - agreement with chorus",
          "url": "https://www.crowninfrastructure.govt.nz/wp-content/uploads/2018/07/fact-sheet-agreement-with-chorus.pdf"
        }
      ]
    }
  ]
}
```

**Comment by lgs85** [comment]
+1 to this

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflect the latest proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
