### ISSUE TITLE
International connections

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#72]
The supply side research surfaced several examples of datasets that include details of the international connections available at nodes:

* [Uganda (pg 12)](https://www.ict.go.ug/wp-content/uploads/2018/06/Infrastructure-Sharing-Policy-UGANDA-Zero-Draft.pdf)
* [Togo (pg 28)](https://drive.google.com/file/d/1gwyIT6K5t1CgVluwJp4-dbL5ftiVgF2U/view)
* [Uganda (UETCL)](https://uetcl.go.ug/wp-content/uploads/2021/02/PRESENT-AND-FUTURE-FIBER-OPTIC-NETWORK-Feb-2021.pdf)
* [Burundi (pg 30)](https://arct.gov.bi/wp-content/uploads/2021/12/rapportinditic2020.pdf)
* [Ghana](https://wholesale.vodafone.com.gh/coverage/)
* [Algeria](https://www.flickr.com/photos/ssong/12661619584/in/photostream/lightbox/)
* [Uganda - UETCL (pg 2)](https://uetcl.go.ug/wp-content/uploads/2020/05/DWDM-network-uganda-uetcl.pdf)

Some publishers list only the name of the country for each connection and some list more specific locations (regions, cities, towns etc.).

**Proposal**

Add an `internationalConnections` property to `Node`. Make `internationalConnections` an array of `Address` objects to allow publishers to disclose locations of varying specificity. Require that `.country` is always populated.

**Example**

```json
{
  "nodes": [
    {
      "internationalConnections": [
        {
          "region": "Mwanza",
          "country": "TZ"
        }
      ]
    }
  ]
}
```

**Comment by lgs85** [comment]
This sounds fine to me. I do wonder if `internationalConnections` is sufficiently unambiguous, but all alternatives I can think of (`internationalConnectionDestinations`) are a bit long. A sufficiently detailed description should be fine.

I also think we should tighten up the terminology between this and `node.type`, which has a 'borderCrossing' code. Maybe we change 'borderCrossing' to 'internationalConnection' in the node type codelist, and add a reference to the `internationalConnections` object in the relevant codelist description?

**Comment by duncandewhurst** [comment]
I think that there might be a difference between a node with international connections and a border crossing as it is currently defined:

> The point at which a fibre cable crosses either an international boundary or the coastline of the operator’s country.

Whereas a node with international connections might not be located at the border, like the Nkenda node with the connection to Beni on [UETCL's map](http://web.archive.org/web/20220728015553/https://uetcl.go.ug/wp-content/uploads/2021/02/PRESENT-AND-FUTURE-FIBER-OPTIC-NETWORK-Feb-2021.pdf):

![image](https://user-images.githubusercontent.com/19265814/188748254-f104b40a-8b5b-4d0c-a966-16a9f02f4237.png)

So I am not sure aligning the terminology is a good idea. However, including a reference to `internationalConnections` in the description of the 'borderCrossing' code sounds good.

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflect the latest proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
