### ISSUE TITLE
Consider renaming links to spans

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/open-fibre-data-standard#83]
To avoid clashes with `links`, we've had to choose alternative names for properties that should be called `links` in both https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/75 and https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/51

This issue is to consider whether we should revert to the 'spans' terminology initially suggested by the technical working group.

I'm putting this issue in the beta milestone as I don't think we'll have time to make such a change for the alpha release.

**Comment by lgs85** [comment]
Agree that `links` has a lot of potential for confusion... ultimately it comes down to whether there is an alternative that will be widely understood. Would be great to get some feedback on this from domain expert stakeholders.

**Comment by duncandewhurst** [comment]
We've not heard any feedback on this yet and I'm reluctant to make a fundamental change to terminology without further input so I'm going to take this out of the beta milestone for now.

**Comment by stevesong** [comment]
Span has always been the more apt term from my perspective as 'link' is used in so many different ways in various access technologies.  Link layer, link budget, etc.

**Comment by lgs85** [comment]
Adding back into the beta milestone!
