### ISSUE TITLE
Exclude codes with a status of 'Further clarification needed' from codelists

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#86]
In #46 we describe the codes currently included in the Node type codelist, codes that require further clarification, and codes to be omiitted. At present the [reference page](https://open-fibre-data-standard.readthedocs.io/en/latest/reference/codelists.html#nodetype) includes any code that does not have an Airtable status of 'Omit'. 

We suggest that these should be excluded from the reference pages unless a strong case is made for inclusion. I have added a new status in Airtable of 'Further clarification needed' and updated the relevant code. We now need to update the `update-from-airtable` function to exclude these from the codelists.

I think that this just involves updating the [following line](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/main/manage.py#L267):

```python
if code_fields["Status"] != "Omit":
```

To something like:

```python
if code_fields["Status"] not in ["Omit","Further clarification needed"]:
```
There are some other places in the script where the "Omit" status is used for exclusion, and we may want to consider updating these too. I'd suggest considering this a one-off and only updating for codelist codes.

**Comment by duncandewhurst** [comment]
Yep, that sounds right to me.
