### ISSUE TITLE
Clarify semantics around link supplier

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#87]
The [conceptual model working paper](https://docs.google.com/document/d/1lEaoUmGr9RATMo_wuM9hLF2oOu22bh_M03JiPXbj-Iw/edit) discusses the idea of a 'supplier' for a link. It would be good to have a clear definition of what is meant by this. Specifically, should a supplier refer to:

- the builder/installer, i.e. the company that installs the cable
- the supplier, i.e. the company that the cable is purchased from
- the manufacturer, i.e. the company that manufacturers the cable.

**PROPOSAL**
Based on comments from the technical working group on the working paper and slides (e.g. [here](https://docs.google.com/presentation/d/11zMvDUpmM-dyopzESq-EUkM6vLx_Tga_dCG_Cwd4E1Q/edit#slide=id.g12b208a231c_0_418) and [here](https://docs.google.com/document/d/1lEaoUmGr9RATMo_wuM9hLF2oOu22bh_M03JiPXbj-Iw/edit?disco=AAAAYA3v2eY)) it appears as though the builder/installer is the most relevant organisation here. We therefore propose to define a link supplier as:

> The organisation responsible for installing the cable for this link.

Based on comments in the working paper, each link would have one supplier. 

This issue is to check whether this interpretation is correct and to explore alternative descriptions of link suppliers.

**Comment by duncandewhurst** [comment]
The alpha schema and codelists added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/101 reflects the latest proposal in this issue.

This issue will remain open against the beta milestone to gather feedback from the alpha consultation.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now.
