### ISSUE TITLE
Organisation classification/type

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#88]
The steering committee meeting notes from 3/12/2021 raised the concept of an organisation type, with 'Telco', 'Bank', 'Government', and 'Other' as suggested codes.

The demand side research and supply side research did not uncover examples of such a field being used, and organisation *roles* are covered in a separate field (see the [reference](https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#components)). We therefore propose to omit this field from the alpha standard.

**Comment by duncandewhurst** [comment]
We've not heard any further feedback on this issue so I'm going to close it for now. It can be reopened if it comes up again.
