### ISSUE TITLE
Consider how to keep fibre type definitions up to date

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#93]
We are using the [ITU-T recommmendations G.651.1-G/657](https://www.itu.int/rec/T-REC-G/en) to describe fibre types. Given that we are using a subset of the recommendations, we need to consider how to best keep the codelist up-to-date.

**Comment by duncandewhurst** [comment]
If we can't automate this, we can at least add instructions to the handbook on how to check for updates to the list.

**Comment by duncandewhurst** [comment]
Since the fibreType codelist is short and the ITU-T recommendations change infrequently, I don't think it's worth the effort to automate this. https://github.com/Open-Telecoms-Data/standard-development-handbook/pull/26 adds instructions for manually updating the fibreType codelist.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/standard-development-handbook/pull/26
